#!/bin/bash

yum remove firewalld -y

yum -y install wget net-tools
wget -q -O - https://www.atomicorp.com/installers/atomic | sh

yum -y install openvas

sed -i '/^#.*unixsocket/s/^# //' /etc/redis.conf

systemctl enable redis && systemctl restart redis

openvas-setup
